---
- name: Set autostart dir
  ansible.builtin.set_fact:
    autostart_dir: "/home/{{ ansible_user }}/.config/lxsession/LXDE-pi"

- name: Create auto start dir in ansible user home
  ansible.builtin.file:
    path: "{{ autostart_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user | default(ansible_user_id) }}"
    recurse: true

- name: Copy autostart script
  ansible.builtin.template:
    src: "{{ os_type }}/autostart.j2"
    dest: "{{ autostart_dir }}/autostart"
    mode: 0755
