version: "3.9"
name: magic-mirror-sonartests
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile.sonar
    env_file:
      - frontend.env
    networks:
      - magic-mirror-sonar_ext-sonar-network
  middleware:
    build:
      context: ./middleware
      dockerfile: docker/Dockerfile.sonar
    env_file:
      - middleware.env
    networks:
      - magic-mirror-sonar_ext-sonar-network

networks:
  magic-mirror-sonar_ext-sonar-network:
    external: true
