export enum ServerStateKeysEnum {
    hourly_weather,
    daily_weather,
    current_weather,
    auth_status,
    time,
    birthdays,
    weather_icon,
    events,
    events_day,
    tasks,
    user_settings,
    geocode,
    calendar_list,
    min_time,
}
