version: "3.9"
name: magic-mirror-sonartests
services:
  frontend:
    build:
      context: ../frontend
      dockerfile: docker/Dockerfile.sonar
    env_file:
      - frontend.env
    networks:
      - magic-mirror-sonar_ext-sonar-network
  backend:
    build:
      context: ../backend
      dockerfile: docker/Dockerfile.sonar
    env_file:
      - backend.env
    networks:
      - magic-mirror-sonar_ext-sonar-network

networks:
  magic-mirror-sonar_ext-sonar-network:
    external: true
