version: "3.9"
name: magic-mirror-test
services:
  frontend:
    build:
      context: ../frontend
      dockerfile: docker/Dockerfile.test
      args:
        NODE_IMG_VERSION: ${NODE_IMG_VERSION}
    volumes:
      - ../frontend/src:/opt/src
      - ../frontend/public:/opt/public
    depends_on:
      - backend
    env_file:
      - frontend.env
  backend:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile.test
      args:
        NODE_IMG_VERSION: ${NODE_IMG_VERSION}
    volumes:
      - ../backend/src:/opt/src
      - ../backend/ssl:/etc/express
    env_file:
      - backend.env
