version: "3.9"
name: magic-mirror-test
services:
  frontend:
    build:
      context: ../frontend
      dockerfile: docker/Dockerfile.test
      args:
        NODE_IMG_VERSION: ${NODE_IMG_VERSION}
    volumes:
      - ../frontend/src:/opt/src
      - ../frontend/public:/opt/public
    depends_on:
      - middleware
    env_file:
      - frontend.env
  middleware:
    build:
      context: ./middleware
      dockerfile: docker/Dockerfile.test
      args:
        NODE_IMG_VERSION: ${NODE_IMG_VERSION}
    volumes:
      - ../middleware/src:/opt/src
      - ../middleware/ssl:/etc/express
    env_file:
      - middleware.env
