ARG NODE_IMG_VERSION=24-alpine3.23
ARG NODE_ENV=development
ARG YARN_VERSION=4.12.0

FROM node:${NODE_IMG_VERSION}

ENV NODE_PATH=./src
ENV NODE_ENV=${NODE_ENV}

RUN apk --no-cache add ca-certificates \
    && rm -rf /var/cache/apk/*

COPY rootCA.pem /usr/local/share/ca-certificates/rootCa.crt

RUN update-ca-certificates

WORKDIR /opt

COPY . .

RUN mv ssl /etc/express

RUN corepack enable && corepack prepare yarn@${YARN_VERSION} --activate

RUN yarn install

CMD [ "yarn", "dev" ]
